#
# ~/.bashrc
#

export EDITOR=vim

export SERVICES=services

export ELASTIC_VERSION="1.5.2"
export ELASTIC_HOME="${SERVICES}/elasticsearch-${ELASTIC_VERSION}/"
export ELASTIC_TAR="elasticsearch-${ELASTIC_VERSION}.tar.gz"
export MARVEL_FILENAME="marvel-latest.zip"

export LOGSTASH_VERSION="1.5.4"
export LOGSTASH_HOME="${SERVICES}/logstash-${LOGSTASH_VERSION}/"
export LOGSTASH_TAR="logstash-${LOGSTASH_VERSION}.tar.gz"

export KIBANA_VERSION="4.1.2"
export KIBANA_HOME="${SERVICES}/kibana-${KIBANA_VERSION}-linux-x64/"
export KIBANA_TAR="kibana-${KIBANA_VERSION}-linux-x64.tar.gz"

export SCREEN_SESSION=$(screen -ls | sed -nre 's/\s*([0-9]+\.worksession).*/\1/p')

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

